version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: master
  versioning-strategy: widen
  ignore:
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.8.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.7
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: webpack
    versions:
    - 4.44.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
